exports.blogs = [
    {
        title: 'Blog 1',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In dictum non consectetur a erat nam at lectus urna. Sed cras ornare arcu dui vivamus arcu felis. Eu turpis egestas pretium aenean. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Scelerisque eleifend donec pretium vulputate sapien. Semper risus in hendrerit gravida rutrum. Est ante in nibh mauris cursus mattis. Lobortis mattis aliquam faucibus purus. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Senectus et netus et malesuada. Dolor morbi non arcu risus. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Viverra mauris in aliquam sem fringilla ut.

        Pharetra massa massa ultricies mi quis hendrerit. Et tortor consequat id porta. Eget lorem dolor sed viverra. Mauris commodo quis imperdiet massa. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Neque gravida in fermentum et. In est ante in nibh mauris cursus mattis molestie. Tincidunt id aliquet risus feugiat in ante metus. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Commodo elit at imperdiet dui accumsan sit amet. Scelerisque mauris pellentesque pulvinar pellentesque.
        
        Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Est ultricies integer quis auctor elit. Et magnis dis parturient montes nascetur. Volutpat lacus laoreet non curabitur. Risus sed vulputate odio ut enim. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Consequat id porta nibh venenatis cras sed felis eget velit. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Tortor aliquam nulla facilisi cras fermentum odio eu. Ultricies lacus sed turpis tincidunt id aliquet risus. Sem viverra aliquet eget sit amet tellus cras. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Integer quis auctor elit sed vulputate.
        
        Semper quis lectus nulla at volutpat diam. Diam vel quam elementum pulvinar etiam non quam. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Elit sed vulputate mi sit amet mauris commodo. Placerat orci nulla pellentesque dignissim enim sit amet. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Mauris vitae ultricies leo integer. Lectus nulla at volutpat diam.
        
        Praesent tristique magna sit amet. Sit amet venenatis urna cursus eget. Blandit aliquam etiam erat velit scelerisque in dictum. Tellus at urna condimentum mattis pellentesque id. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Enim nulla aliquet porttitor lacus. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Mus mauris vitae ultricies leo. Non consectetur a erat nam at lectus urna duis convallis. Tincidunt praesent semper feugiat nibh sed. Pellentesque nec nam aliquam sem et tortor consequat id. Ipsum a arcu cursus vitae congue. Duis ut diam quam nulla porttitor massa id neque. Sit amet facilisis magna etiam tempor.`,
        img: 'https://images.unsplash.com/photo-1625037680463-0051698d6dda?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80'
    },

    {
        title: 'Blog 2',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In dictum non consectetur a erat nam at lectus urna. Sed cras ornare arcu dui vivamus arcu felis. Eu turpis egestas pretium aenean. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Scelerisque eleifend donec pretium vulputate sapien. Semper risus in hendrerit gravida rutrum. Est ante in nibh mauris cursus mattis. Lobortis mattis aliquam faucibus purus. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Senectus et netus et malesuada. Dolor morbi non arcu risus. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Viverra mauris in aliquam sem fringilla ut.

        Pharetra massa massa ultricies mi quis hendrerit. Et tortor consequat id porta. Eget lorem dolor sed viverra. Mauris commodo quis imperdiet massa. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Neque gravida in fermentum et. In est ante in nibh mauris cursus mattis molestie. Tincidunt id aliquet risus feugiat in ante metus. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Commodo elit at imperdiet dui accumsan sit amet. Scelerisque mauris pellentesque pulvinar pellentesque.
        
        Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Est ultricies integer quis auctor elit. Et magnis dis parturient montes nascetur. Volutpat lacus laoreet non curabitur. Risus sed vulputate odio ut enim. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Consequat id porta nibh venenatis cras sed felis eget velit. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Tortor aliquam nulla facilisi cras fermentum odio eu. Ultricies lacus sed turpis tincidunt id aliquet risus. Sem viverra aliquet eget sit amet tellus cras. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Integer quis auctor elit sed vulputate.
        
        Semper quis lectus nulla at volutpat diam. Diam vel quam elementum pulvinar etiam non quam. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Elit sed vulputate mi sit amet mauris commodo. Placerat orci nulla pellentesque dignissim enim sit amet. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Mauris vitae ultricies leo integer. Lectus nulla at volutpat diam.
        
        Praesent tristique magna sit amet. Sit amet venenatis urna cursus eget. Blandit aliquam etiam erat velit scelerisque in dictum. Tellus at urna condimentum mattis pellentesque id. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Enim nulla aliquet porttitor lacus. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Mus mauris vitae ultricies leo. Non consectetur a erat nam at lectus urna duis convallis. Tincidunt praesent semper feugiat nibh sed. Pellentesque nec nam aliquam sem et tortor consequat id. Ipsum a arcu cursus vitae congue. Duis ut diam quam nulla porttitor massa id neque. Sit amet facilisis magna etiam tempor.`,
        img: 'https://images.unsplash.com/photo-1625037680463-0051698d6dda?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80'
    },

    {
        title: 'Blog 3',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In dictum non consectetur a erat nam at lectus urna. Sed cras ornare arcu dui vivamus arcu felis. Eu turpis egestas pretium aenean. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Scelerisque eleifend donec pretium vulputate sapien. Semper risus in hendrerit gravida rutrum. Est ante in nibh mauris cursus mattis. Lobortis mattis aliquam faucibus purus. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Senectus et netus et malesuada. Dolor morbi non arcu risus. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Viverra mauris in aliquam sem fringilla ut.

        Pharetra massa massa ultricies mi quis hendrerit. Et tortor consequat id porta. Eget lorem dolor sed viverra. Mauris commodo quis imperdiet massa. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Neque gravida in fermentum et. In est ante in nibh mauris cursus mattis molestie. Tincidunt id aliquet risus feugiat in ante metus. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Commodo elit at imperdiet dui accumsan sit amet. Scelerisque mauris pellentesque pulvinar pellentesque.
        
        Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Est ultricies integer quis auctor elit. Et magnis dis parturient montes nascetur. Volutpat lacus laoreet non curabitur. Risus sed vulputate odio ut enim. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Consequat id porta nibh venenatis cras sed felis eget velit. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Tortor aliquam nulla facilisi cras fermentum odio eu. Ultricies lacus sed turpis tincidunt id aliquet risus. Sem viverra aliquet eget sit amet tellus cras. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Integer quis auctor elit sed vulputate.
        
        Semper quis lectus nulla at volutpat diam. Diam vel quam elementum pulvinar etiam non quam. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Elit sed vulputate mi sit amet mauris commodo. Placerat orci nulla pellentesque dignissim enim sit amet. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Mauris vitae ultricies leo integer. Lectus nulla at volutpat diam.
        
        Praesent tristique magna sit amet. Sit amet venenatis urna cursus eget. Blandit aliquam etiam erat velit scelerisque in dictum. Tellus at urna condimentum mattis pellentesque id. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Enim nulla aliquet porttitor lacus. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Mus mauris vitae ultricies leo. Non consectetur a erat nam at lectus urna duis convallis. Tincidunt praesent semper feugiat nibh sed. Pellentesque nec nam aliquam sem et tortor consequat id. Ipsum a arcu cursus vitae congue. Duis ut diam quam nulla porttitor massa id neque. Sit amet facilisis magna etiam tempor.`,
        img: 'https://images.unsplash.com/photo-1625037680463-0051698d6dda?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80'
    },

    {
        title: 'Blog 4',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In dictum non consectetur a erat nam at lectus urna. Sed cras ornare arcu dui vivamus arcu felis. Eu turpis egestas pretium aenean. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Scelerisque eleifend donec pretium vulputate sapien. Semper risus in hendrerit gravida rutrum. Est ante in nibh mauris cursus mattis. Lobortis mattis aliquam faucibus purus. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Senectus et netus et malesuada. Dolor morbi non arcu risus. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Viverra mauris in aliquam sem fringilla ut.

        Pharetra massa massa ultricies mi quis hendrerit. Et tortor consequat id porta. Eget lorem dolor sed viverra. Mauris commodo quis imperdiet massa. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Neque gravida in fermentum et. In est ante in nibh mauris cursus mattis molestie. Tincidunt id aliquet risus feugiat in ante metus. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Commodo elit at imperdiet dui accumsan sit amet. Scelerisque mauris pellentesque pulvinar pellentesque.
        
        Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Est ultricies integer quis auctor elit. Et magnis dis parturient montes nascetur. Volutpat lacus laoreet non curabitur. Risus sed vulputate odio ut enim. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Consequat id porta nibh venenatis cras sed felis eget velit. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Tortor aliquam nulla facilisi cras fermentum odio eu. Ultricies lacus sed turpis tincidunt id aliquet risus. Sem viverra aliquet eget sit amet tellus cras. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Integer quis auctor elit sed vulputate.
        
        Semper quis lectus nulla at volutpat diam. Diam vel quam elementum pulvinar etiam non quam. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Elit sed vulputate mi sit amet mauris commodo. Placerat orci nulla pellentesque dignissim enim sit amet. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Mauris vitae ultricies leo integer. Lectus nulla at volutpat diam.
        
        Praesent tristique magna sit amet. Sit amet venenatis urna cursus eget. Blandit aliquam etiam erat velit scelerisque in dictum. Tellus at urna condimentum mattis pellentesque id. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Enim nulla aliquet porttitor lacus. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Mus mauris vitae ultricies leo. Non consectetur a erat nam at lectus urna duis convallis. Tincidunt praesent semper feugiat nibh sed. Pellentesque nec nam aliquam sem et tortor consequat id. Ipsum a arcu cursus vitae congue. Duis ut diam quam nulla porttitor massa id neque. Sit amet facilisis magna etiam tempor.`,
        img: 'https://images.unsplash.com/photo-1625037680463-0051698d6dda?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80'
    },

    {
        title: 'Blog 5',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In dictum non consectetur a erat nam at lectus urna. Sed cras ornare arcu dui vivamus arcu felis. Eu turpis egestas pretium aenean. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Scelerisque eleifend donec pretium vulputate sapien. Semper risus in hendrerit gravida rutrum. Est ante in nibh mauris cursus mattis. Lobortis mattis aliquam faucibus purus. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Senectus et netus et malesuada. Dolor morbi non arcu risus. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Viverra mauris in aliquam sem fringilla ut.

        Pharetra massa massa ultricies mi quis hendrerit. Et tortor consequat id porta. Eget lorem dolor sed viverra. Mauris commodo quis imperdiet massa. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Neque gravida in fermentum et. In est ante in nibh mauris cursus mattis molestie. Tincidunt id aliquet risus feugiat in ante metus. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Commodo elit at imperdiet dui accumsan sit amet. Scelerisque mauris pellentesque pulvinar pellentesque.
        
        Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Est ultricies integer quis auctor elit. Et magnis dis parturient montes nascetur. Volutpat lacus laoreet non curabitur. Risus sed vulputate odio ut enim. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Consequat id porta nibh venenatis cras sed felis eget velit. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Tortor aliquam nulla facilisi cras fermentum odio eu. Ultricies lacus sed turpis tincidunt id aliquet risus. Sem viverra aliquet eget sit amet tellus cras. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Integer quis auctor elit sed vulputate.
        
        Semper quis lectus nulla at volutpat diam. Diam vel quam elementum pulvinar etiam non quam. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Elit sed vulputate mi sit amet mauris commodo. Placerat orci nulla pellentesque dignissim enim sit amet. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Mauris vitae ultricies leo integer. Lectus nulla at volutpat diam.
        
        Praesent tristique magna sit amet. Sit amet venenatis urna cursus eget. Blandit aliquam etiam erat velit scelerisque in dictum. Tellus at urna condimentum mattis pellentesque id. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Enim nulla aliquet porttitor lacus. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Mus mauris vitae ultricies leo. Non consectetur a erat nam at lectus urna duis convallis. Tincidunt praesent semper feugiat nibh sed. Pellentesque nec nam aliquam sem et tortor consequat id. Ipsum a arcu cursus vitae congue. Duis ut diam quam nulla porttitor massa id neque. Sit amet facilisis magna etiam tempor.`,
        img: 'https://images.unsplash.com/photo-1625037680463-0051698d6dda?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80'
    },

];